image: node:14-alpine
stages:
  - build
  - development
pages:
  stage: development
  artifacts:
    paths:
      - src
  script:
    - rm -rf src
    - cp dist/index.html dist/404.html
    - mv dist src
  only:
    - develop
site-build:
  stage: build
  image: node:latest
  script:
    - npm install -g @angular/cli@10.1.3
    - npm install
    - ng build --configuration production --output-path=dist # Explicitly set the output path
    - pwd # Print the working directory
    - ls -la # List the contents of the working directory
  artifacts:
    name: artifact-$CI_COMMIT_REF_NAME
    paths:
      - dist
    expire_in: 1h
  only:
    - develop
