image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build -- --output-path=./dist/out --configuration production

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv dist/out public
  artifacts:
    paths:
      - public
  only:
    - develop
