image: node:14-alpine

stages:
  - setup
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG} # This will create a separate cache for each branch
  paths:
    - node_modules/

setup:
  stage: setup
  script:
    - npm ci # Use 'npm ci' instead of 'npm install' for faster and more reliable dependency installation
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day # This will ensure that the cache doesn't grow indefinitely
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'

build:
  stage: build
  script:
    - npm install -g @angular/cli@10.1.3
    - ng build --configuration production
  artifacts:
    paths:
      - public
  needs: [setup] # The 'needs' keyword ensures that the 'setup' job is executed before the 'build' job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'

deploy:
  stage: deploy
  script:
    # Add your deployment script here
  environment:
    name: production
  only:
    - develop
