---
mage: node:14-alpine
stages:
  - build
  - development
pages:
  stage: development
  artifacts:
    paths:
      - public
  script:
    - rm -rf public
    - cp dist/index.html dist/404.html
    - mv dist public
  only:
    - develop
site-build:
  stage: build
  image: node:latest
  artifacts:
    name: artifact-$CI_COMMIT_REF_NAME
    paths:
      - dist
    expire_in: 1h
  script:
    - npm install
    - npm install -g env-cmd
    - npm run buildProd
  only:
    - develop
