image: node:14-alpine

stages:
  - build

cache:
  paths:
    - node_modules/

site-build:
  stage: build
  script:
    - npm install -g @angular/cli@10.1.3
    - npm install
    - npm run buildProd
    - rm -rf public
    - mkdir -p public/develop
    - cp dist/index.html dist/404.html
    - mv dist/* public/develop
  artifacts:
    paths:
      - public
  only:
    - develop
