image: node:14-alpine

stages:
  - build

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm ci
    - ng build --prod --base-href "/my-project-name/"
    - mv dist/my-project-name/index.html dist/my-project-name/404.html
    # Copy all files in dist to public directory to enable GitLab Pages deployment
    - cp -R dist/my-project-name/. public/
  artifacts:
    paths:
      - public
  only:
    - develop # or whichever branch you want to deploy from
