---
image: node:14-alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
stages:
  - setup
  - build
  - deploy
setup:
  stage: setup
  script:
    - npm ci
    - npm install -g @angular/cli@10.1.3
build:
  stage: build
  script:
    - ng build --configuration production
  artifacts:
    paths:
      - dist/
  only:
    - develop
deploy:
  stage: deploy
  script:
    - rm -rf public
    - cp dist/index.html dist/404.html
    - mv dist public
  only:
    - develop
