image: node:14-alpine

stages:
  - build
  - development

pages:
  stage: development
  artifacts:
    paths:
      - public
  script:
    - npm install
    - npm install -g env-cmd
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public/
  only:
    - develop

site-build:
  stage: build
  image: node:latest
  artifacts:
    name: artifact-$CI_COMMIT_REF_NAME
    paths:
      - dist
    expire_in: 1h
  script:
    - npm install
    - npm install -g env-cmd
    - npm run build
  only:
    - develop
