---
image: node:14-alpine
stages:
  - build
  - deploy
pages:
  stage: deploy
  artifacts:
    paths:
      - public
  script:
    - rm -rf public
    - cp dist/index.html dist/404.html
    - mv dist public
  only:
    - develop
site-build:
  stage: build
  image: node:latest
  script:
    - npm install -g @angular/cli@10.1.3
    - npm install
    - ng build --configuration production --base-href=/develop/
    - pwd
    - ls -la
  artifacts:
    name: artifact-$CI_COMMIT_REF_NAME
    paths:
      - dist
    expire_in: 1h
  only:
    - develop
