export const environment = {
  production: false,

  //LIVE SERVER URL
  saveurl: 'https://hrmaven.works/signup',
  loginurl: 'https://hrmaven.works/login',
<<<<<<< HEAD
  // Forgoturl: 'https://hrmaven.works/forgotpassword',
  // Reseturl: 'https://hrmaven.works/resetpassword',
  // personalurl: 'http://localhost:3000/addpersonaldata',

=======
  Forgoturl: 'https://hrmaven.works/forgotpassword',
  Reseturl: 'https://hrmaven.works/resetpassword',
>>>>>>> e93873ec19fe568a8257b4979ea9da9fe7b0c9e9
  url: 'https://hrmaven.works/user-profile',
  auth: 'https://hrmaven.works/auth',
  createData: 'https://hrmaven.works/api/create',
  getData: 'https://hrmaven.works/api/find',
  deleteData: 'https://hrmaven.works/api/',
  getLeave: 'https://hrmaven.works/api/leave//',
  updateData: 'https://hrmaven.works/attendance',
  getAttd: 'https://hrmaven.works/attendance',
  updatempdata: 'https://hrmaven.works/api/update',
  getuid: 'https://hrmaven.works/api/uid',
  report: 'https://hrmaven.works/attendance/report',
  profile: 'https://hrmaven.works/user-profile',
  updateleave: 'https://hrmaven.works/attendance/update',
<<<<<<< HEAD
  // getemail: 'https://hrmaven.works/getemails/email',

  // //LOCAL URL
  // updateleave: 'http://localhost:3000/attendance/update',
  // saveurl: 'http://localhost:3000/signup',
  // loginurl: 'http://localhost:3000/login',
  Forgoturl: 'http://localhost:3000/forgotpassword',
  Reseturl: 'http://localhost:3000/resetpassword',
  personalurl: 'http://localhost:3000/addpersonaldata',
  updatepersonaldata :'http://localhost:3000/updateperosnal/:userId',
  // url: 'http://localhost:3000/user-profile',
  // auth: 'http://localhost:3000/auth',
  // createData: 'http://localhost:3000/api/create',
  // getData: 'http://localhost:3000/api/find',
  // deleteData: 'http://localhost:3000/api/',
  // getLeave: 'http://localhost:3000/api/leave//',
  // updateData: 'http://localhost:3000/attendance',
  // getAttd: 'http://localhost:3000/attendance',
  // updatempdata: 'http://localhost:3000/api/update',
  // getuid: 'http://localhost:3000/api/uid',
  // report: 'http://localhost:3000/attendance/report',
  // profile: 'http://localhost:3000/user-profile',
  getemail : 'http://localhost:3000/getemails/email',
=======
  getemail: 'https://hrmaven.works/getemails/email',
  attendance:'https://hrmaven.works/attendance/date/attendance',
  attendancecard:'https://hrmaven.works/attendance/date/attendancecard',
  attendancegraph:'https://hrmaven.works/attendance/date/report',
  getreseturl: 'https://hrmaven.works/resetpassword',
  getpwd : 'https://hrmaven.works/userprofilepwd',

  // //LOCAL URL

//   attendancegraph:'http://localhost:3000/attendance/date/report',
//   getpwd : 'http://localhost:3000/userprofilepwd',
//   attendancecard:'http://localhost:3000/attendance/date/attendancecard',
//   attendance:'http://localhost:3000/attendance/date/attendance',
//   updateleave: 'http://localhost:3000/attendance/update',
//   saveurl: 'http://localhost:3000/signup',
//   loginurl: 'http://localhost:3000/login',
//   Forgoturl: 'http://localhost:3000/forgotpassword',
//   Reseturl: 'http://localhost:3000/resetpassword',
//   getreseturl: 'http://localhost:3000/resetpassword',
//   url: 'http://localhost:3000/user-profile',
//   auth: 'http://localhost:3000/auth',
//   createData: 'http://localhost:3000/api/create',
//   getData: 'http://localhost:3000/api/find',
//   deleteData: 'http://localhost:3000/api/',
//   getLeave: 'http://localhost:3000/api/leave//',
//   updateData: 'http://localhost:3000/attendance',
//   getAttd: 'http://localhost:3000/attendance',
//   updatempdata: 'http://localhost:3000/api/update',
//   getuid: 'http://localhost:3000/api/uid',
//   report: 'http://localhost:3000/attendance/report',
//   profile: 'http://localhost:3000/user-profile',
//  getemail : 'http://localhost:3000/getemails/email',
>>>>>>> e93873ec19fe568a8257b4979ea9da9fe7b0c9e9
};
